### PR TITLE
Highlight configuration docs in readup

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
Increase tuning option visibility.

cc @codeclimate/review @noahd1

### CODE REVIEW

**Comment by ABaldwinHunter** [comment]
screen shot 2016-02-08 at 6 31 46 pm

**Comment by ABaldwinHunter** [comment]
Before:

screen shot 2016-02-08 at 6 33 28 pm

**Comment by ABaldwinHunter** [comment]
@noahd1 ready for another look. Added a pic

**Comment by ABaldwinHunter** [comment]
Post talk, alternate 1:
screen shot 2016-02-09 at 12 20 44 pm

**Comment by ABaldwinHunter** [comment]
alternate 2:
screen shot 2016-02-09 at 12 20 52 pm

**Comment by pbrisbin** [comment]
@ABaldwinHunter the new copy LGTM, but I also don't have a problem with the old copy so I'd be fine merging this or closing it as stale. Can we try to do either one soon?

**Pull request merged**
