### PR TITLE
set rubocop settings to our standard style

### PR DESCRIPTION
**Pull request by wfleming**
Updating these while convenient, and also since we haven't had PR integration turned for a while to check that's working.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Should you just copy in the one from the style guide?

**Comment by wfleming** [comment]
> Should you just copy in the one from the style guide?

I did?

**Comment by pbrisbin** [comment]
Oh, the diff was so small, I mistook it for a modification of a `codeclimate --init`ed one. Not just syncing up with the style guide.

LGTM.

**Comment by wfleming** [comment]
@pbrisbin I think I had copied in the styleguide one a while ago, so this was just a sync of changes since then. Hence the small diff.

**Pull request merged**
