### PR TITLE
Update example yaml to use colon hash syntax

### PR DESCRIPTION
**Pull request by efueger**
Consistent with Duplication Help Doc (https://docs.codeclimate.com/v1.0/docs/duplication#section-enable-the-engine).

### CODE REVIEW

**Comment by maxjacobson** [comment]
This LGTM

Do you think we should update to use this syntax in the default .codeclimate.yml we generate for repos with `codeclimate init`?

**Comment by efueger** [comment]
@maxjacobson - exactly what #cx was thinking. Not sure about the ramifications/amount of work this would involve.

**Comment by maxjacobson** [comment]
Sure. This PR look OK to merge. I recommend talking to @GordonDiggs about actioning that work

**Comment by GordonDiggs** [comment]
😄  https://handbook.codeclimate.net/engineering/work_requests

**Comment by maxjacobson** [comment]
Heh, wasn't sure whether to link it on an OSS PR 😅

**Comment by GordonDiggs** [comment]
@maxjacobson good call - deleted!

**Pull request merged**
