### PR TITLE
Include mass in issue description

### PR DESCRIPTION
**Pull request by ABaldwinHunter**
- Increase mass visibility
- Increase parity with Code Climate classic duplication reporting

The mass is already presented in the issue content readup, but somewhat obfuscated.

@codeclimate/review 

Replaces https://github.com/codeclimate/codeclimate-duplication/pull/77/commits

### CODE REVIEW

**Comment by noahd1** [comment]
The mass in the readup is really buried. I would consider removing it entirely FWIW.

**Comment by pbrisbin** [comment]
LGTM

**Comment by ABaldwinHunter** [comment]
:+!

**Comment by ABaldwinHunter** [comment]
Screenshot from CLI:

screen shot 2016-01-27 at 5 49 13 pm

**Pull request merged**
