### PR TITLE
Do not run relase-images on forked prs

### PR DESCRIPTION
**Pull request by fede-moya**
We are receiving failed builds from prs open by the community due to running the `relase-images` ci job. This work removes this job for those cases.

See https://github.com/codeclimate/codeclimate-duplication/pull/364

### CODE REVIEW

**Comment by fede-moya** [comment]
This theory was wrong the CI was building due to a missing dependency on the `codelcimate-parser` base image.

**Review by filipesperandio — COMMENTED** [review]
Skipping CI for those, how we are going to validate them instead?

**Comment by fede-moya** [comment]
> Skipping CI for those, how we are going to validate them instead?
@filipesperandio it's not the entire ci, just the job for releasing images. Do you think releasing images is a necessary step for validating prs ?

**Comment by filipesperandio** [comment]
🤦 I was tired...

**Review by filipesperandio — APPROVED** [review]
I am OK shipping this anyways, but seems like we only actually release images for master and channel-* branches here: https://github.com/codeclimate/codeclimate-duplication/blob/master/bin/deploy#L10-L13

**Comment by fede-moya** [comment]
> I am OK shipping this anyways, but seems like we only actually release images for master and channel-* branches here: https://github.com/codeclimate/codeclimate-duplication/blob/master/bin/deploy#L10-L13

mmmm, interesting because it is getting triggered on https://github.com/codeclimate/codeclimate-duplication/pull/366

**Review by filipesperandio — APPROVED** [review]
Yeah, that build seems to break on `docker login`, even before the `bin/deploy` call, but I agree this is even better as we skip the step entirely, have CIRCLE env vars checked on Circle related files and make it more visible.

👍

**Comment by fede-moya** [comment]
@filipesperandio Exactly it was breaking before the `bin/deploy`, could you merge it ? 🙏🏼

**Pull request merged**
